### PR TITLE
Handle missing refresh tokens in the quickstarts

### LINKED ISSUE #16: Error: refresh token must be passed in or set as part of setAccessToken
He utilizado el ejemplo de quickstart.php para Google Calendar y funciona todo correcto hasta que pasan algo más de dos horas y me devuelve un error al intentar refrescar el token al expirar.

He mirado en muchos foros y no funciona nada de lo que se indica.

Por favor, me puede ayudar.

**Sample:**

## ERROR
`PHP Fatal error:  Uncaught LogicException: refresh token must be passed in or set as part of setAccessToken in C:\www\medel\pru\vendor\google\apiclient\src\Google\Client.php:258
Stack trace:
#0 C:\www\medel\pru\quickstart.php(51): Google_Client->fetchAccessTokenWithRefreshToken(NULL)
#1 C:\www\medel\pru\quickstart.php(59): getClient()
#2 {main}
  thrown in C:\www\medel\pru\vendor\google\apiclient\src\Google\Client.php on line 258

Fatal error: Uncaught LogicException: refresh token must be passed in or set as part of setAccessToken in C:\www\medel\pru\vendor\google\apiclient\src\Google\Client.php:258
Stack trace:
#0 C:\www\medel\pru\quickstart.php(51): Google_Client->fetchAccessTokenWithRefreshToken(NULL)
#1 C:\www\medel\pru\quickstart.php(59): getClient()
#2 {main}
  thrown in C:\www\medel\pru\vendor\google\apiclient\src\Google\Client.php on line 258`

## Steps to Reproduce the Problem

  1.He seguido los pasos que se indican en la guía de Google (https://developers.google.com/calendar/quickstart/php)

## Specifications

  - PHP version (`php -v`): PHP Vr. 7.2.6
  - OS: Windows 10

### PR DESCRIPTION
**Pull request by erickoledadevrel**
Significant changes to the logic around handling access tokens. Ensures that `fetchAccessTokenWithRefreshToken()` is only called when a refresh token is present, and falls back to requesting a new token when one isn't. Sets the `prompt` OAuth2 parameter to ensure that the user sees the select account and consent screens, to ensure a refresh token is returned.

Prototyping on the Calendar quickstart, and will replicate out to the others once approved.

Fixes #16.

### CODE REVIEW

**Comment by grant** [comment]
@erickoledadevrel Let's follow up on this.

**Comment by erickoledadevrel** [comment]
Updated the rest of the quickstarts, tested them each by hand. Made some small fixes to the Apps Script quickstart, since the curly braces in the strings were being interpreted as variables.

File: admin-sdk/directory/quickstart.php [hunk 1]
```diff
@@ -32,39 +32,41 @@ function getClient()
...
+        $accessToken = json_decode(file_get_contents($tokenPath), true);
+        $client->setAccessToken($accessToken);
+    }
 
-        // Exchange authorization code for an access token.
-        $accessToken = $client->fetchAccessTokenWithAuthCode($authCode);
+    // If there is no previous token or it's expired.
+    if ($client->isAccessTokenExpired()) {
+        // Refresh the token if possible, else fetch a new one.
+        if($client->getRefreshToken()) {
```
Comment (grant) [inline admin-sdk/directory/quickstart.php]: Nit, spacing: `if(`

Comment (erickoledadevrel) [reply admin-sdk/directory/quickstart.php]: Done
